---
- name: Preparing Workstation
  hosts: workstation
  become: true
  gather_facts: true

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Add repositories
      tags:
        - repositories
      include_tasks: tasks/repos.yml
    - name: Install packages
      tags:
        - packages
      include_tasks: tasks/packages.yml
