---
- block:
  - name: Check for vscode repo
    stat: path=/etc/yum.repos.d/vscode.repo
    register: fedora_vscode_installed

  - name: Import Microsoft GPG key
    rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Enable vscode repo
    yum_repository:
      name: code
      description: Visual Studio Code
      file: vscode
      baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
      gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
      gpgcheck: yes
    when: not fedora_vscode_installed.stat.exists

- block:
  - name: Check for sublime-text repo
    stat: path=/etc/yum.repos.d/sublime-text.repo
    register: fedora_sublime_text_installed

  - name: Install sublime-text repo
    command: dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    when: not fedora_sublime_text_installed.stat.exists

- block:
  - name: Import RPM Fusion GPG key Free
    rpm_key:
      state: present
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
  
  - name: Import RPM Fusion GPG key Non-Free
    rpm_key:
      state: present
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

  - name: Check for RPM Fusion Free repo
    stat: path=/etc/yum.repos.d/rpmfusion-free.repo
    register: fedora_rpm_fusion_free_installed

  - name: Check for RPM Fusion Nonfree repo
    stat: path=/etc/yum.repos.d/rpmfusion-nonfree.repo
    register: fedora_rpm_fusion_nonfree_installed

  - name: Install RPM Fusion repo rpms
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
      state: present
    when: not fedora_rpm_fusion_free_installed.stat.exists

  - name: Install RPM Fusion Nonfree repo rpms
    dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
      state: present
    when: not fedora_rpm_fusion_nonfree_installed.stat.exists

- block:
  - name: Add the flathub flatpak repository remote to the user installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user
